[[crates]]
name = "core"
paths = ["term"]
packages = ["apps"]
description = "test core"

[[crates]]
name = "shared"
paths = ["error"]
description = '''
paths = [
    "api_errors",
    "shipping",
]
[[crates]]
name = "connect"
paths = ["account", "billing"]
packages = ["apps"]
[[crates]]
name = "shared"
paths = ["error"]
description = "test shared"'''