[project]
name = "payjp-openapi"
version = "0.0.0"
private = true
description = "Just a command runner"
requires-python = ">=3.12"
dependencies = [
    "jsonnet>=0.20.0",
]

[tool.setuptools]
script-files = ["scripts/myscript1", "scripts/myscript2"]